-- 获取所有表的，以及表的字段
SELECT 
    a.RDB$RELATION_NAME,
    b.RDB$FIELD_NAME,
    b.RDB$FIELD_ID,
    d.RDB$TYPE_NAME,
    c.RDB$FIELD_LENGTH,
    c.RDB$FIELD_SCALE
FROM RDB$RELATIONS AS a
    INNER JOIN RDB$RELATION_FIELDS AS b ON a.RDB$RELATION_NAME = b.RDB$RELATION_NAME
    INNER JOIN RDB$FIELDS AS c ON b.RDB$FIELD_SOURCE = c.RDB$FIELD_NAME
    INNER JOIN RDB$TYPES AS d ON c.RDB$FIELD_TYPE = d.RDB$TYPE
WHERE a.RDB$SYSTEM_FLAG = 0
    AND d.RDB$FIELD_NAME = 'RDB$FIELD_TYPE'
ORDER BY a.RDB$RELATION_NAME, b.RDB$FIELD_ID;

--查询所有的用户表
SELECT RDB$RELATION_NAME FROM RDB$RELATIONS WHERE RDB$SYSTEM_FLAG = 0 AND RDB$VIEW_BLR IS NULL;